[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py311", "py312"]

[tool.isort]
profile = "black"
py_version = 311
line_length = 88
skip = [".venv", ".linuxvenv"]
